### ISSUE TITLE
Bug isUpdated() causing issues with saving

### ISSUE THREAD

**Issue by NicholasJohnsonDev** [rhorton5/CSCD-488-490-Senior-Project#7]
Bug with isUpdated() in each of the [forms].cs but existed before this branch (I definitely made this bug), just wanted to note it somewhere.

**Comment by rhorton5** [comment]
SpecimenDataGridView_EnterCell() function could be causing saving issues.

One particular bug I've noticed is that you will get the Confirm Save MessageBox despite only just opening the SpceimensForm and then exiting out.  C# allows you to use class variables even if they are uninitialized.  So you can have cases where isUpdated() returns true even though you only entered SpecimensForm and then returned to the Main Menu.  isUpdated() has null values for the class variables that are being passed as true.

https://github.com/rhorton5/CSCD-488-490-Senior-Project/blob/6c2462c3875361fbeb7878bf1a19d20792b35447/Team%206%20Senior%20Project/SpecimensForm.cs#L7-L15

This would mean as well that the CellEntered Events are not called when you first enter the Forms.  I have not tested it out yet with swapping between different rows and seeing whether or not that alters the data inside the DataGridView, but I think that could be a problem as well.

https://github.com/rhorton5/CSCD-488-490-Senior-Project/blob/6c2462c3875361fbeb7878bf1a19d20792b35447/Team%206%20Senior%20Project/SpecimensForm.cs#L329-L337

isUpdated() is not really the biggest issue, but I think it's the methods that create the class variables that it relies for the if statements that might set it up to fail.

https://github.com/rhorton5/CSCD-488-490-Senior-Project/blob/6c2462c3875361fbeb7878bf1a19d20792b35447/Team%206%20Senior%20Project/SpecimensForm.cs#L315-L327
